## loc 인덱서

In [1]:
import pandas as pd
import numpy as np

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [6]:
df = pd.DataFrame(np.arange(10,22).reshape(3,4),
              index=['a','b','c'],
              columns=["A","B","C","D"])
df

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [7]:
df.loc["a"]  # Series

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [8]:
# df.loc['A'] 열 단독 인덱싱 불가

In [9]:
df.loc['b':'c']

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [10]:
df['b':'c']

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [11]:
df.loc[['b','c']]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [12]:
df.loc["b"]  # Series

A    14
B    15
C    16
D    17
Name: b, dtype: int32

In [13]:
df.loc[["b"]]  # DataFrame

    A   B   C   D
b  14  15  16  17

In [15]:
df.loc[['b','c']]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [17]:
df[['B','C']]

    B   C
a  11  12
b  15  16
c  19  20

#### Boolean selection

In [18]:
df.A

a    10
b    14
c    18
Name: A, dtype: int32

In [19]:
df.A > 15

a    False
b    False
c     True
Name: A, dtype: bool

In [20]:
df.loc[df.A > 15]

    A   B   C   D
c  18  19  20  21

In [21]:
# 불리언 시리즈를 반환하는 함수 작성
def sel_row(df):
    return df.A > 15
sel_row(df)

a    False
b    False
c     True
Name: A, dtype: bool

In [22]:
df.loc[sel_row(df)]

    A   B   C   D
c  18  19  20  21

In [24]:
df2 = pd.DataFrame(np.arange(10,26).reshape(4,4),
                  columns=['a','b','c','d'])
df2

    a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [25]:
df2.loc[1:2]

    a   b   c   d
1  14  15  16  17
2  18  19  20  21

In [26]:
df2[1:2] # 위치 인덱싱

    a   b   c   d
1  14  15  16  17

In [27]:
df2.loc[0,'a']

10

In [29]:
df

    A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [28]:
df.loc['a','A']

10

In [30]:
df.loc['a','A'] = 50
df

    A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

In [31]:
df.loc[['a','b']]['A'] # Series

a    50
b    14
Name: A, dtype: int32

In [32]:
df.loc[['a','b'],'A']  # Series

a    50
b    14
Name: A, dtype: int32

In [33]:
df.loc[['a','b'],['A']]  # DataFrame

    A
a  50
b  14

In [34]:
df.loc['a']

A    50
B    11
C    12
D    13
Name: a, dtype: int32

In [35]:
df.loc[['a']]

    A   B   C   D
a  50  11  12  13

In [36]:
df.loc['a',:]

A    50
B    11
C    12
D    13
Name: a, dtype: int32

In [37]:
df.loc[['a'],:]

    A   B   C   D
a  50  11  12  13

In [38]:
df.loc['a', 'B':'C'] # Series

B    11
C    12
Name: a, dtype: int32

In [39]:
df.loc[['a']]  # df

    A   B   C   D
a  50  11  12  13

In [41]:
df.loc[['a'], 'B':'C']  # df

    B   C
a  11  12

In [43]:
df.loc['a', ['B','C']]  # Series

B    11
C    12
Name: a, dtype: int32

In [44]:
df.loc['b':]

    A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [45]:
df.loc['b':,'A']

b    14
c    18
Name: A, dtype: int32

In [46]:
df.loc['b':]['A']

b    14
c    18
Name: A, dtype: int32

In [47]:
df.loc['b':][['A']]

    A
b  14
c  18

In [48]:
df.loc['b':,['A']]

    A
b  14
c  18

In [49]:
df.loc['b':,'A':'A']

    A
b  14
c  18

In [50]:
df.loc['a':'b']

    A   B   C   D
a  50  11  12  13
b  14  15  16  17

In [51]:
df.loc[['a','b']]

    A   B   C   D
a  50  11  12  13
b  14  15  16  17

In [52]:
df.loc[['a','b']][['B','D']]

    B   D
a  11  13
b  15  17

In [53]:
df.loc[['a','b'],['B','D']]

    B   D
a  11  13
b  15  17

## iloc 인덱서(위치 인덱스)

- 라벨이 아닌 위치를 나타내는 **정수** 인덱스만 받는다
- 위치 정수값은 0부터 시작

In [54]:
df

    A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

In [55]:
df.iloc[0,1]

11

In [56]:
df.iloc[0:2,1:2]

    B
a  11
b  15

In [57]:
df.iloc[0:2]

    A   B   C   D
a  50  11  12  13
b  14  15  16  17

In [58]:
df.iloc[0:2, 1]

a    11
b    15
Name: B, dtype: int32

In [59]:
df.iloc[2]

A    18
B    19
C    20
D    21
Name: c, dtype: int32

In [60]:
df.iloc[2,1:2]

B    19
Name: c, dtype: int32

In [62]:
df.iloc[2:3,1:2]

    B
c  19

In [63]:
df

    A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

In [64]:
df.iloc[0:1,-2:]

    C   D
a  12  13

In [65]:
df.iloc[0,-2:]

C    12
D    13
Name: a, dtype: int32

In [66]:
df.iloc[[0,1],[1,2]]

    B   C
a  11  12
b  15  16

- 원소들을 분류하여 개수를 세는 함수: `value_counts()`

In [67]:
df = pd.DataFrame({'num_legs':[2,4,4,6],
                  'num_wings':[2,0,0,0]},
                 index=['falcon','dog','cat','ant'])
df

        num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [68]:
df.num_legs

falcon    2
dog       4
cat       4
ant       6
Name: num_legs, dtype: int64

In [70]:
df.num_legs.value_counts()

4    2
2    1
6    1
Name: num_legs, dtype: int64

In [71]:
df.value_counts()

num_legs  num_wings
4         0            2
2         2            1
6         0            1
dtype: int64