### 데이터프레임 생성

#### 리스트로 데이터프레임 만들기

- `DataFrame([[list1],[list2]])` - 리스트 안에 리스트 형태로 인수 전달(2차원 리스트 형태)
- 각 list는 한 행
- 행의 원소 개수가 다르면 None 값
- index 인수값이 없으면 기본 인덱스(위치 인덱스) 생성됨

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([['a','b','c'],['a','a','g'],['a','a']])
df

   0  1     2
0  a  b     c
1  a  a     g
2  a  a  None

#### 딕셔너리로 데이터프레임 생성
- dict의 key -> column name

In [3]:
df1 = pd.DataFrame(
{
    'A':[90,80,70],
    'B':[85,98,75],
    'C':[88,99,77],
    'D':[87,89,86]
}, index = [1, 2, 3])
df1

    A   B   C   D
1  90  85  88  87
2  80  98  99  89
3  70  75  77  86

In [5]:
data = {
    "2015":[9904312,3448737,2890451,2466052],
    "2010":[9631482,2293191,2632035,2000002],
    "2005":[9762546,3512547,2517680,2456016],
    "2000":[9853972,3655437,2466338,2473990],
    "지역":["수도권","경상권","수도권","경상권"],
    "2010-2015 증가율":[0.0283,0.0163,0.0982,0.0141]
}
df3 = pd.DataFrame(data)
df3

      2015     2010     2005     2000   지역  2010-2015 증가율
0  9904312  9631482  9762546  9853972  수도권         0.0283
1  3448737  2293191  3512547  3655437  경상권         0.0163
2  2890451  2632035  2517680  2466338  수도권         0.0982
3  2466052  2000002  2456016  2473990  경상권         0.0141

In [6]:
columns=["지역", "2000", "2005", "2010", "2015", "2010-2015 증가율"]
index=["서울", "부산", "인천", "대구"]
df3 = pd.DataFrame(data, index=index, columns=columns)
df3

     지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  2293191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

#### 시리즈로 데이터프레임 생성
- 각 Series로 인덱스 -> columnname

In [7]:
a = pd.Series([100,200,300], ['a','b','d'])
b = pd.Series([101,201,301], ['a','b','k'])
c = pd.Series([110,210,310], ['a','b','c'])

In [8]:
pd.DataFrame([a,b,c], index=[100,101,102])

         a      b      d      k      c
100  100.0  200.0  300.0    NaN    NaN
101  101.0  201.0    NaN  301.0    NaN
102  110.0  210.0    NaN    NaN  310.0

#### csv 데이터로 데이터프레임 생성

In [12]:
train_data = pd.read_csv('./data/train.csv')
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

- `read_csv` 함수 파라미터
    - `sep`: 각 데이터 값 구별하기 위한 구분자
    - `header`: header 무시할 경우, None 설정
    - `index_col`: index로 사용할 column 설정
    - `usecols`: 실제로 dataframe에 로딩할 columns만 설정

In [15]:
train_data = pd.read_csv('data/train.csv',
                        index_col = 'PassengerId',
                        usecols=['PassengerId','Survived','Name','Sex','Age'])
train_data.head()

,Survived,Name,Sex,Age
PassengerId,,,,
1,0,"Braund, Mr. Owen Harris",male,22.0
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
3,1,"Heikkinen, Miss. Laina",female,26.0
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
5,0,"Allen, Mr. William Henry",male,35.0

In [17]:
train_data.columns

Index(['Survived', 'Name', 'Sex', 'Age'], dtype='object')

#### index와 column의 이해
1. 인덱스
    - 고유의 값
    - 멀티 인덱스 가능
2. 컬럼
    - 특성
    - 멀티 컬럼 가능

In [18]:
df3

     지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  2293191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [19]:
df3.columns

Index(['지역', '2000', '2005', '2010', '2015', '2010-2015 증가율'], dtype='object')

In [20]:
type(df3.columns)

pandas.core.indexes.base.Index

In [21]:
df3.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [22]:
type(df3.index)

pandas.core.indexes.base.Index

In [23]:
df3.index.name = '도시'
df3.columns.name = '특성'
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  2293191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [24]:
df3.values

array([['수도권', 9853972, 9762546, 9631482, 9904312, 0.0283],
       ['경상권', 3655437, 3512547, 2293191, 3448737, 0.0163],
       ['수도권', 2466338, 2517680, 2632035, 2890451, 0.0982],
       ['경상권', 2473990, 2456016, 2000002, 2466052, 0.0141]], dtype=object)

In [25]:
type(df3.values)

numpy.ndarray

In [26]:
df3.values[0]

array(['수도권', 9853972, 9762546, 9631482, 9904312, 0.0283], dtype=object)

In [27]:
type(df3.values[0])

numpy.ndarray

#### dataframe 데이터 파악하기
- `shape` 속성
- `describe` 함수 - 숫자형 데이터의 통계치 계산
- `info` 함수 - 데이터 타입, 각 아이템의 개수 등 출력

In [28]:
train_data.head()

,Survived,Name,Sex,Age
PassengerId,,,,
1,0,"Braund, Mr. Owen Harris",male,22.0
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
3,1,"Heikkinen, Miss. Laina",female,26.0
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
5,0,"Allen, Mr. William Henry",male,35.0

In [29]:
len(train_data)  # df의 행 수

891

In [30]:
train_data.size  # df의 값의 개수

3564

In [31]:
train_data.shape  # df의 행과 열 수

(891, 4)

In [32]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Name      891 non-null    object
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB

In [33]:
train_data.describe()

         Survived         Age
count  891.000000  714.000000
mean     0.383838   29.699118
std      0.486592   14.526497
min      0.000000    0.420000
25%      0.000000   20.125000
50%      0.000000   28.000000
75%      1.000000   38.000000
max      1.000000   80.000000

#### 데이터프레임 전치

In [34]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  2293191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [35]:
df3.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2000           9853972  3655437  2466338  2473990
2005           9762546  3512547  2517680  2456016
2010           9631482  2293191  2632035  2000002
2015           9904312  3448737  2890451  2466052
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [36]:
df3.T['서울'].values

array(['수도권', 9853972, 9762546, 9631482, 9904312, 0.0283], dtype=object)

In [37]:
df3.T['서울']['2000']

9853972

###  데이터프레임 내용 변경
- 열추가, 열삭제, 내용 갱신

In [38]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  2293191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [39]:
df3["2010-2015 증가율"] * 100

도시
서울    2.83
부산    1.63
인천    9.82
대구    1.41
Name: 2010-2015 증가율, dtype: float64

In [40]:
df3["2010-2015 증가율"]= df3["2010-2015 증가율"] * 100

In [41]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [42]:
df3['비고']=['특별시','광역시','특례시','특례시']
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율   비고
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83  특별시
부산  경상권  3655437  3512547  2293191  3448737           1.63  광역시
인천  수도권  2466338  2517680  2632035  2890451           9.82  특례시
대구  경상권  2473990  2456016  2000002  2466052           1.41  특례시

In [43]:
del df3['비고']
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [44]:
df3.loc['광주'] = ['호남권', 2470000, 2456000, 2453000, 2460000, 1.00]

In [45]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

### 데이터 프레임 인덱싱

1. 열인덱싱

In [47]:
df3['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
광주    호남권
Name: 지역, dtype: object

In [48]:
type(df3['지역'])

pandas.core.series.Series

In [49]:
df3.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
광주    호남권
Name: 지역, dtype: object

In [50]:
df3[['지역']]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권
광주  호남권

In [51]:
type(df3[['지역']])

pandas.core.frame.DataFrame

In [52]:
df3[['2010','2015']]

특성     2010     2015
도시
서울  9631482  9904312
부산  2293191  3448737
인천  2632035  2890451
대구  2000002  2466052
광주  2453000  2460000

In [53]:
#df3[0]  열 이름이 문자열일 경우 수치 인덱스 사용 불가

In [54]:
df5 = pd.DataFrame(np.arange(12).reshape(3,4))
df5

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [55]:
df5[[1,2]]  # 위치 인덱스가 아니고 컬럼명이 숫자로 되어있는 경우

   1   2
0  1   2
1  5   6
2  9  10

In [56]:
np.arange(12)
np.arange(12).reshape(3,4)  # 배열의 차원 변경

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

2. 행 단위 인덱싱

In [57]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

In [59]:
df3[: '서울']  # 첫번째 행 추출

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83

In [60]:
df3['인천':'인천']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [61]:
df3[:1]

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83

In [62]:
df3[0:1]

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83

In [63]:
df3[1:3]  # [시작값: 끝값+1]

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [64]:
df3['부산':'인천']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [65]:
df3['2015']

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
광주    2460000
Name: 2015, dtype: int64

In [66]:
df3['2015']['부산']

3448737

In [67]:
df3[['2015']]

특성     2015
도시
서울  9904312
부산  3448737
인천  2890451
대구  2466052
광주  2460000

In [69]:
df3[['2015']]['부산':'부산']

특성     2015
도시
부산  3448737

In [70]:
# df3[['2015']]['부산'] key error

In [71]:
df = df3[['2005','2010']]
df

특성     2005     2010
도시
서울  9762546  9631482
부산  3512547  2293191
인천  2517680  2632035
대구  2456016  2000002
광주  2456000  2453000

In [72]:
df3[['2005','2010']]['부산':'부산']

특성     2005     2010
도시
부산  3512547  2293191

In [75]:
# df3[['2000':'2010']] 열 인덱싱에 슬라이스 사용 불가

In [73]:
df3.head()

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

#### 행 삭제
- `drop()`함수 사용
- `drop(index=[삭제할 행 인덱스])`
- 원본 반영하지 않음(inplace=True 해야함)

In [76]:
df3.drop(index=['광주'], inplace=True)

In [77]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  2293191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [78]:
df3.drop(columns=['2000'], inplace=True)
df3

특성   지역     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9762546  9631482  9904312           2.83
부산  경상권  3512547  2293191  3448737           1.63
인천  수도권  2517680  2632035  2890451           9.82
대구  경상권  2456016  2000002  2466052           1.41

In [79]:
df3.drop(['대구'], axis=0)

특성   지역     2005     2010     2015  2010-2015 증가율
도시
서울  수도권  9762546  9631482  9904312           2.83
부산  경상권  3512547  2293191  3448737           1.63
인천  수도권  2517680  2632035  2890451           9.82

In [80]:
df3.drop(['2010-2015 증가율'], axis=1)

특성   지역     2005     2010     2015
도시
서울  수도권  9762546  9631482  9904312
부산  경상권  3512547  2293191  3448737
인천  수도권  2517680  2632035  2890451
대구  경상권  2456016  2000002  2466052