In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all" # all/last/last_expr(기본값)/none
# 설정변경코드: 변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것

In [2]:
import pandas as pd
import numpy as np

## pandas 데이터처리 및 변환 관련 함수

### 데이터 개수 세기
- `count()`
    - NaN 값은 세지 않음

In [3]:
# 시리즈에서 개수 세기
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [4]:
s.count()

9

### 난수 발생시켜 dataframe 생성
- 난수 `seed(값)`라는 함수 사용 가능
- seed의 의미: 난수 알고리즘에서 사용하는 기본 값으로 시드 값이 같으면 동일한 난수 발생
- 계속 변경되는 난수 받고 싶으면 `Time.time()`

In [9]:
np.random.randint(5)
np.random.randint(5, size=4)

0

array([0, 0, 3, 2])

In [11]:
np.random.seed(3)
np.random.randint(5, size=4)  # 값 고정됨

array([2, 0, 1, 3])

In [12]:
np.random.randint(5, size=4)  # seed 리셋됨

array([0, 0, 0, 3])

In [14]:
# 시드값 매번 다르게 전달되도록 코드 작성
import time
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([1, 3, 2, 1])

In [16]:
np.random.randint(5, size=(4,4))

array([[4, 4, 2, 3],
       [3, 1, 3, 3],
       [1, 2, 3, 4],
       [1, 0, 2, 1]])

In [17]:
np.random.seed(3)
df1 = pd.DataFrame(np.random.randint(5, size=(4,4)))
df1.iloc[2,3]=np.nan
df1

   0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [18]:
df1.count()  # 각열에 대한 원소의 개수 반환

0    4
1    4
2    4
3    3
dtype: int64

In [19]:
import seaborn as sns  # 그래프 패키지

In [20]:
titanic = pd.read_csv('./data/test.csv')
del titanic['Unnamed: 0']
titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [21]:
titanic.tail(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [22]:
titanic.to_csv('./data/test.csv')

In [23]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

### 카테고리 값 세기
- 시리즈 값이 정수, 문자열 등 카테고리 값인 경우에 `시리즈.value_counts()` 메서드를 사용해 각각의 값이 나온 횟수를 셀 수 있음
- `normalize=True`를 사용하면 각 값 및 범주형 데이터의 비율을 계산

In [24]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size=100))
len(s2)

100

In [25]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [26]:
s2.value_counts(normalize=True)

1    0.22
0    0.18
4    0.17
5    0.16
3    0.14
2    0.13
dtype: float64

#### 범주형 데이터에 value_counts() 함수 적용
- 범주형 데이터: 관측 결과가 몇개의 범주 또는 항목의 형태로 나타나는 자료

In [27]:
# 생존 여부 yes/no로 표시되어 있음
titanic['alive'].dtype

dtype('O')

In [28]:
titanic['alive'].value_counts()

no     549
yes    342
Name: alive, dtype: int64

In [29]:
titanic['alive'].value_counts(normalize=True)

no     0.616162
yes    0.383838
Name: alive, dtype: float64

In [30]:
titanic['alive'].value_counts(normalize=True) * 100

no     61.616162
yes    38.383838
Name: alive, dtype: float64

In [31]:
# 남녀 비율
titanic['sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [32]:
titanic['sex'].value_counts(normalize=True) * 100

male      64.758698
female    35.241302
Name: sex, dtype: float64

In [33]:
titanic[['sex','alive']].head(2)

      sex alive
0    male    no
1  female   yes

In [34]:
titanic[['sex','alive']].value_counts()

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
dtype: int64

In [35]:
type(titanic[['sex','alive']].value_counts())

pandas.core.series.Series

In [36]:
pd.DataFrame(titanic[['sex','alive']].value_counts())

                0
sex    alive
male   no     468
female yes    233
male   yes    109
female no      81

### 정렬함수
- `sort_index(ascending=True/False)`: 인덱스 기준
- `sort_value(ascending=True/False)`: 데이터 값 기준

#### 시리즈 함수

In [37]:
s2

0     5
1     3
2     4
3     0
4     1
     ..
95    4
96    5
97    2
98    4
99    3
Length: 100, dtype: int32

In [38]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [39]:
s2.value_counts().sort_index()

0    18
1    22
2    13
3    14
4    17
5    16
dtype: int64

In [41]:
s2.value_counts().sort_index(ascending=False)

5    16
4    17
3    14
2    13
1    22
0    18
dtype: int64

In [40]:
s2.value_counts().sort_values()

2    13
3    14
5    16
4    17
0    18
1    22
dtype: int64

In [42]:
s2.value_counts().sort_values(ascending=False)

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [43]:
df1

   0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

#### 데이터프레임 정렬

In [44]:
# df1.sort_values() TypeError by

In [45]:
df1.sort_values(by=0)

   0  1  2    3
1  0  0  0  3.0
0  2  0  1  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [46]:
df1.sort_values(by=0, ascending=False)

   0  1  2    3
0  2  0  1  3.0
2  2  3  1  NaN
3  2  0  4  4.0
1  0  0  0  3.0

In [47]:
df = pd.DataFrame({'num_legs':[2,4,4,6],
                  'num_wings':[2,0,0,0]},
                 index=['falcon','dog','cat','ant'])
df

        num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [48]:
df.sort_index()

        num_legs  num_wings
ant            6          0
cat            4          0
dog            4          0
falcon         2          2

In [49]:
df.sort_index(ascending=False)

        num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

### 행/열 합계
- `df.sum()`
- 열의 합계: `sum(axis=0)`
- 행의 합계: `sum(axis=1)`

In [51]:
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df2

   0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [52]:
# 각 행의 합계
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [53]:
# 긱 열의 합계
df2.sum(axis=0)

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [54]:
# axis 인수 생략하면 기본값이 0(각 열의 합계)
df2.sum()

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [55]:
df2['total'] = df2[[0,1,2,3,4,5,6,7]].sum(axis=1)
df2

   0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

#### df의 기본 함수
- `mean()`
- `min()`
- `max()`

In [56]:
# 긱 열의 평균
df2.mean(axis=0)

0         6.00
1         8.25
2         6.25
3         6.00
4         3.75
5         2.50
6         1.25
7         4.00
total    38.00
dtype: float64

In [57]:
# 각 행의 평균
df2.mean(axis=1)

0    7.777778
1    7.555556
2    9.111111
3    9.333333
dtype: float64

In [58]:
# 긱 열의 최소값
df2.min(axis=0)

0         4
1         7
2         2
3         4
4         0
5         0
6         0
7         1
total    34
dtype: int64

In [59]:
# 긱 행의 최소값
df2.min(axis=1)

0    0
1    2
2    0
3    0
dtype: int64

In [60]:
# 긱 열의 최대값
df2.max(axis=0)

0         9
1         9
2         9
3         9
4         9
5         7
6         4
7         7
total    42
dtype: int64

In [61]:
# 긱 행의 최대값
df2.max(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [62]:
df2.loc['max_data'] = df2[[0,1,2,3,4,5,6,7]].max(axis=0)

In [63]:
df2

            0    1    2    3    4    5    6    7  total
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0   35.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0   34.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0   41.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0   42.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0    NaN